"""Added required tables

Revision ID: 1818566eeba3
Revises: 821813484e59
Create Date: 2023-04-04 17:50:57.596133

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1818566eeba3'
down_revision = '821813484e59'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
