"""Added required tables

Revision ID: 821813484e59
Revises: 6d581ca27b37
Create Date: 2023-03-28 07:40:51.560180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '821813484e59'
down_revision = '6d581ca27b37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('favourites', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'favourites')
    # ### end Alembic commands ###
