"""Added required tables

Revision ID: 92892c37b49a
Revises: 79619d8fc893
Create Date: 2023-04-19 09:59:10.245606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92892c37b49a'
down_revision = '79619d8fc893'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
