"""Added required tables

Revision ID: bea7dbd37d70
Revises: f4aa7280314f
Create Date: 2023-04-12 10:19:11.959290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bea7dbd37d70'
down_revision = 'f4aa7280314f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
