"""Added required tables

Revision ID: c41419ea05b4
Revises: 61116efa13cb
Create Date: 2023-04-14 09:50:37.093965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c41419ea05b4'
down_revision = '61116efa13cb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tz', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tz')
    # ### end Alembic commands ###
