"""Added required tables

Revision ID: c476d189e73e
Revises: bc410ffa081b
Create Date: 2023-04-14 07:24:36.674941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c476d189e73e'
down_revision = 'bc410ffa081b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_name'), 'users', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_name'), table_name='users')
    # ### end Alembic commands ###
