version: "3.9"

services:
  web_project_backend:
    container_name: web_project_backend
    hostname: backend
    user: '1000:1000'
    restart: unless-stopped
    build: 
      context: ./backend/
      network: host
    networks:
      - web_project-network
    volumes:
      - ./backend/:/backend/
    ports:
      - 5001:5001

  web_project_frontend:
    container_name: web_project_frontend
    hostname: frontend
    # user: '1000:1000'
    restart: unless-stopped
    build: 
      context: ./frontend/
      network: host
    networks:
      - web_project-network
    volumes:
      - ./frontend/src/:/var/www
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/default.conf:/etc/nginx/conf.d/default.conf
      # - ./frontend/:/frontend/
    ports:
      - 6001:6001

  postgres:
    image: postgres:15.2
    container_name: web_project_postgres
    hostname: postgres
    restart: unless-stopped
    networks:
      - web_project-network
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./postgres/data/:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  worker:
    build: ./backend
    container_name: web_project_worker
    command: celery -A worker.celery worker --loglevel=info --logfile=logs/celery.log
    volumes:
      - ./backend:/usr/src/app
    environment:
      - CELERY_BROKER_URL=redis://redis:6381/0
      - CELERY_RESULT_BACKEND=redis://redis:6381/0
    depends_on:
      - web_project_backend
      - redis

  redis:
    image: redis:latest
    container_name: web_project_redis
    ports:
      - 6381:6381

  dashboard:
    build: ./backend
    container_name: web_project_dashboard
    command: celery --broker=redis://redis:6381/0 flower --port=5555
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=redis://redis:6381/0
      - CELERY_RESULT_BACKEND=redis://redis:6381/0
    depends_on:
      - web_project_backend
      - redis
      - worker

networks:
  web_project-network:
    driver: bridge
