"""Added required tables

Revision ID: 91db622adab5
Revises: bea7dbd37d70
Create Date: 2023-04-12 10:25:08.253307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91db622adab5'
down_revision = 'bea7dbd37d70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
