"""Added required tables

Revision ID: bc410ffa081b
Revises: 95862d66160e
Create Date: 2023-04-13 16:34:15.656041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc410ffa081b'
down_revision = '95862d66160e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
