"""Added required tables

Revision ID: d7c7e17d73ac
Revises: c41419ea05b4
Create Date: 2023-04-17 09:01:53.252099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7c7e17d73ac'
down_revision = 'c41419ea05b4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
