"""Added required tables

Revision ID: e27a2844c65e
Revises: 70192b86c2b0
Create Date: 2023-04-19 08:40:04.482862

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e27a2844c65e'
down_revision = '70192b86c2b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes_vector',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name_notes', sa.String(length=100), nullable=True),
    sa.Column('text_notes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_vector_name_notes'), 'notes_vector', ['name_notes'], unique=False)
    op.create_index(op.f('ix_notes_vector_text_notes'), 'notes_vector', ['text_notes'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notes_vector_text_notes'), table_name='notes_vector')
    op.drop_index(op.f('ix_notes_vector_name_notes'), table_name='notes_vector')
    op.drop_table('notes_vector')
    # ### end Alembic commands ###
