"""Added required tables

Revision ID: 53b589ed3195
Revises: 92892c37b49a
Create Date: 2023-04-19 10:01:34.524520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53b589ed3195'
down_revision = '92892c37b49a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notes_vector_name_notes', table_name='notes_vector')
    op.drop_index('ix_notes_vector_text_notes', table_name='notes_vector')
    op.drop_table('notes_vector')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes_vector',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name_notes', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('text_notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='notes_vector_pkey')
    )
    op.create_index('ix_notes_vector_text_notes', 'notes_vector', ['text_notes'], unique=False)
    op.create_index('ix_notes_vector_name_notes', 'notes_vector', ['name_notes'], unique=False)
    # ### end Alembic commands ###
