"""Added required tables

Revision ID: 61116efa13cb
Revises: c476d189e73e
Create Date: 2023-04-14 09:46:27.156835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61116efa13cb'
down_revision = 'c476d189e73e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tz', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'tz')
    # ### end Alembic commands ###
