"""Added required tables

Revision ID: 6d581ca27b37
Revises: 88941ed59954
Create Date: 2023-03-27 10:13:45.699885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d581ca27b37'
down_revision = '88941ed59954'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('text_notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'text_notes')
    # ### end Alembic commands ###
