"""Added required tables

Revision ID: 75e6506a4ec6
Revises: 53b589ed3195
Create Date: 2023-04-24 12:00:47.447201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75e6506a4ec6'
down_revision = '53b589ed3195'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
