"""Added required tables

Revision ID: 79619d8fc893
Revises: e27a2844c65e
Create Date: 2023-04-19 09:18:15.298230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79619d8fc893'
down_revision = 'e27a2844c65e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=100), nullable=True))
    op.drop_index('ix_users_name', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_name', 'users', ['name'], unique=False)
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
