"""Added required tables

Revision ID: 95862d66160e
Revises: bd6c4a20baf7
Create Date: 2023-04-12 13:36:48.083842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95862d66160e'
down_revision = 'bd6c4a20baf7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
