"""Added required tables

Revision ID: 95d48c5259db
Revises: d7c7e17d73ac
Create Date: 2023-04-17 14:54:46.999164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95d48c5259db'
down_revision = 'd7c7e17d73ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_notes_name_notes'), 'notes', ['name_notes'], unique=False)
    op.create_index(op.f('ix_notes_text_notes'), 'notes', ['text_notes'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notes_text_notes'), table_name='notes')
    op.drop_index(op.f('ix_notes_name_notes'), table_name='notes')
    # ### end Alembic commands ###
