"""empty message

Revision ID: b1c1010db69f
Revises: 21ca1702ca7a
Create Date: 2023-03-24 11:52:26.621364

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1c1010db69f'
down_revision = '21ca1702ca7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
